version: 2
jobs:
  build:
    docker:
      - image: node:7
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Commands"
          command: |
            echo 'PATH=$PWD/prism/bin:$PATH' >> $BASH_ENV
            npm install
            mkdir -p prism/bin
            ./test/prism.sh
            npm test
            npm run test:typescript
